### ISSUE TITLE
Move packages into their own repo and update README?

### ISSUE THREAD

**Issue by pat-s** [RevolutionAnalytics/foreach#11]
Currently both the {foreach} and {iterators} pkg lives in the same repo, within a dir called `pkgs`.

This is quite uncommon for the R community and might scare some people away from contributing.

Also a markdown formatted README introducing the package could help making these projects more welcoming to potential contributors.

**Comment by Hong-Revo** [comment]
That's the plan; a wart is that I don't actually have permissions to create a repo under the Revo org....

**Comment by Hong-Revo** [comment]
https://github.com/RevolutionAnalytics/iterators

**Comment by Hong-Revo** [comment]
New structure in the "staging" branch.

**Comment by HenrikBengtsson** [comment]
Another thing you could do is `git tag 1.4.8` and `git push --tags` to tag commits corresponding to the different CRAN releases. (That way you can also `install_github("org/repos@version")`)
