### ISSUE TITLE
Foreach set comprehension 

### ISSUE THREAD

**Issue by jannikbuhr** [RevolutionAnalytics/foreach#12]
In his exciting talk at RStudio::Conf 2020 (https://resources.rstudio.com/rstudio-conf-2020/parallel-computing-with-r-using-foreach-future-and-other-packages-bryan-lewis), Bryan mentioned the similarity between `foreach` and haskells list comprehension and shows on his slides the example

```
foreach(1:10, j:10) %:%
  when(i < j) %dopar% {
    i + j
  }
```

However, in practice this produces an empty list because unlike in Haskell, `foreach` evaluates the expression not for each combination of `i` and `j` but only traverses the length of the shortest vector.

A shorter example:

``` r
foreach(i = 1:2, j = 1:2) %do% c(i, j)
#> [[1]]
#> [1] 1 1
#> 
#> [[2]]
#> [1] 2 2
```

But the corresponding list comprehension in Haskell does this:

```
[(i, j) | i <- [1..2], j <- [1..2]]
-- [(1,1),(1,2),(2,1),(2,2)]
```

Is this the intended behavior?

**Comment by Hong-Revo** [comment]
I don't know Haskell. What did you expect the 1st example to produce?

**Comment by jannikbuhr** [comment]
I was assuming that he put the example in his talk because he was expecting it to run over all possible combinations of i and j, thus I assumed

```
foreach(1:10, j:10) %:%
  when(i < j) %dopar% {
    i + j
  }
```

would return something equivalent to what gets printed here:

```
for (i in 1:10) {
  for (j in 1:10) {
    if (i < j) print(i + j)
  }
}
```

But you seem to have a different syntax for this :)

**Comment by Hong-Revo** [comment]
Correct, in fact the foreach syntax deliberately mimics the base R syntax:

```r
foreach(i=1:10) %:% foreach(j=1:10, .combine=c) %:% when(i < j) %do% (i + j)
```
```
[[1]]
[1]  3  4  5  6  7  8  9 10 11

[[2]]
[1]  5  6  7  8  9 10 11 12

[[3]]
[1]  7  8  9 10 11 12 13

[[4]]
[1]  9 10 11 12 13 14

[[5]]
[1] 11 12 13 14 15

[[6]]
[1] 13 14 15 16

[[7]]
[1] 15 16 17

[[8]]
[1] 17 18

[[9]]
[1] 19

[[10]]
NULL
```
