### ISSUE TITLE
"socketselect" takes long time when the number of process increases.

### ISSUE THREAD

**Issue by toshifumikuroda** [RevolutionAnalytics/foreach#29]
Hi RevolutionAnalytics,

I find "socketSelect" takes long time when I make large number of process .
I am working on R4.0.3 in Windows10. The computer has 32 core (Ryzen 3970X).
Because the CPU have 32 core, I try to parallelize my code for 32 process.
However, when I register 32 process, socketSelect takes a long time.
It does not occur when I run the same code in Ubuntu in WSL2.
For your information, I attached screen shots of profvis that use 8, 12 and 32 process.

Thank you,
Tooshifumi

8 Process
![8core](https://user-images.githubusercontent.com/12432689/111107166-b4846c80-8599-11eb-8f13-48415d0c3053.jpg)
12 Process
![12core](https://user-images.githubusercontent.com/12432689/111107162-b2baa900-8599-11eb-943f-a1bc27d51c77.jpg)
32 Process
![32core](https://user-images.githubusercontent.com/12432689/111107169-b5b59980-8599-11eb-8e43-27b7fe1ebea4.jpg)

**Comment by HenrikBengtsson** [comment]
I suspect this has to do with the **parallel** package that **doParallel** build upon.

My recommendation would be the reproduce the problem with only `parallel::parLapply()` and report to the R devel mailing list.

My $0.02

**Comment by toshifumikuroda** [comment]
Thank you for your recommendation. I will follow your recommendation.
