### ISSUE TITLE
R crash accessing object created in parallel, foreach()

### ISSUE THREAD

**Issue by tghoward** [RevolutionAnalytics/foreach#30]
I am moving to a new Azure VM and all of a sudden getting crashes and errors in crazy places I never have before. I don't know if this is related to `foreach` but if not I'm hoping you can point me in the correct direction.  I've tracked down one spot where I can reproduce the problem with the following code

```
# load packages
library(foreach)
library(randomForest)
library(iterators)
library(parallel)
library(doParallel)

numCores <- detectCores() - 1
ntrees <- 8000
treeSubs <- ntrees/numCores
# initialize
cl <- makeCluster(numCores)
registerDoParallel(cl)
# dummy datasets
x <- as.data.frame(matrix(runif(100000), 20000))
y <- gl(2, 10000)

parRf <- foreach(ntree = rep(treeSubs,numCores), .combine = randomForest::combine,
                        .packages = 'randomForest', .multicombine = TRUE) %dopar%
                                randomForest(x=x, y=y,
                        importance=TRUE,mtry=2,ntree = ntree,
                        replace = TRUE
  )

z <- matrix(runif(1000), 200)

pred <- predict(parRf, z, type = "prob")
```

Notice it is the predict step that causes the failure, but when I make the randomForest call not in parallel, the predict step works fine. Or if I make the data sets smaller, it also works. In RStudio I get the grey "bomb" and in RGui it just disappears.

Here are some details of the crash report from the Windows Event Log. Is it indicating that memory registers are getting dropped and then the `predict` is trying to access them again? (and thus illegal access?)

```
Faulting application name: rsession.exe, version: 1.1.463.0, time stamp: 0x5bd11fb5
Faulting module name: randomForest.dll, version: 0.0.0.0, time stamp: 0x609f54bd
Exception code: 0xc0000005
Fault offset: 0x0000000000001b42
Faulting process id: 0x1e48
Faulting application start time: 0x01d752f21b6d7a79
Faulting application path: C:\Program Files\RStudio\bin\x64\rsession.exe
```

My session info:
```
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] doParallel_1.0.16   iterators_1.0.13    randomForest_4.6-14 foreach_1.5.1      

loaded via a namespace (and not attached):
[1] compiler_4.0.5   tools_4.0.5      codetools_0.2-18
> 
```
Thanks in advance for any tips.

Edit:  I guess I should add that I asked over in SO, but the only reply so far is someone who *can* get the predict to run. Perhaps this person is using a different OS? (they haven't said). 
https://stackoverflow.com/questions/67722541/r-crash-accessing-object-created-in-parallel-foreach

Again, thanks.

**Comment by hongooi73** [comment]
`ntree=8000` will create N random forests each with 8000 trees. Do you REALLY want that?

**Comment by tghoward** [comment]
@hongooi73, this is a mock dataset and setup to show the seg fault. Are you saying that we should expect the system to fail like this when using large values like this? 

Also, note that it is written as `ntrees=8000` (with an "s") and these are divided among cores as `treeSubs`.  And then `treeSubs` are replicated among cores with `ntree = rep(treeSubs,numCores)`  (without an "s") so I think you are possibly misreading?

Thanks for looking at it. Can you replicate this behavior (on a Windows)?

**Comment by tghoward** [comment]
Interesting, I wonder if it is related to this statement in the `parallel` package:  "Note that all these methods of communication use serialize/unserialize to send R objects between processes. This has limits (typically hundreds of millions of elements) which a well designed parallelized algorithm should not approach."  

From here, bottom of page 2.  https://stat.ethz.ch/R-manual/R-devel/library/parallel/doc/parallel.pdf

**Comment by tghoward** [comment]
I have been trying to replicate this behavior with only the parallel package and am unable to do so, suggesting it is something in `foreach` that is causing the crash.

**Comment by HenrikBengtsson** [comment]
Hi.

> ... with only the parallel package and am unable to do so ...

It's not clear what you did, but assuming you're using something like `y <- parLapply(cl, X, fun)` with the same cluster object `cl` as before, then my best guess is that you're running out of memory or something, because `registerDoParallel(cl)` is using basically the same machinery as `parLapply()` internally.

To narrow down where the problem is, I suggest that you simplify your `foreach()` to _not_ try to combine the results; that could definitely be a place where you run out of memory.  So, see if what you get with:

```r
message("randomForest() in parallel")
parRf <- foreach(ntree = rep(treeSubs,numCores), .export = c("x", "y"), .packages = 'randomForest') %dopar% {
  randomForest(x=x, y=y, importance=TRUE, mtry=2, ntree = ntree, replace = TRUE)
}

message("combine() results")
parRf <- do.call(randomForest::combine, parRf)

message("predict()")
z <- matrix(runif(1000), 200)
pred <- predict(parRf, z, type = "prob")
```

By looking at the output, you should be able to see how far it made it before crashing. 

Also, try with fewer workers and see if you can it to work with 1, 2, 4, ... workers.

PS. But I admit it's not that you get a "segfault"; running out of memory should not do that.  OTH, that might be how `rsession.exe` handles the problem (don't even know what that is; not using Azure).

**Comment by tghoward** [comment]
@HenrikBengtsson, thanks for the comment. I can get the crash on my laptop as well so it isn't just Azure.  Using your code it still happens during the predict. Here's a screenshot of the crash on my laptop. 

![image](https://user-images.githubusercontent.com/6129193/120889351-9c395200-c5ca-11eb-82a1-c659c37a6c04.png)

I agree that running out of memory should not cause a crash. That's why I opened this issue. 

If you can't replicate I expect if you play around with the size of the input dataset (perhaps to match the memory resources on your computer?) you would eventually be able to, as least on Windows machines.

**Comment by HenrikBengtsson** [comment]
Okay.  Two more comments:

1. How big is the combined `parRF` object, what does `message("Object size: ", objectSize(parRF))` report?  If not too big, maybe you can save it to file `saveRDS()` and attach it here.

2. What is your `numCores` and, more importantly, can you reproduce it with `numCores = 1`, 2, 4, ...?  Or, does it only have with the `numCores` you're happened to use?  That's crucial to know to reproduce.

**Comment by tghoward** [comment]
1. exported, `parRf` is about 21 MB and 19 MB zipped. I've attached the zip. 
[parRF_object.zip](https://github.com/RevolutionAnalytics/foreach/files/6604121/parRF_object.zip)

2. I've got 4 cores on my laptop. In just a few tries right now I can only replicate this behavior with 3 cores. On a 64-core VM, I can replicate this error with 63, 62, 61 cores (haven't tried fewer), but it does not crash with 64 cores. 

3. Adding `stopCluster(cl)` still causes the crash.  (although it might be intermittent)

4. That's because I was using a different computer from my original test box. I can replicate this on these OSs: Windows Server 2016, Windows Server 2019, Windows 10 Home. As you can see, I can also replicate this with various versions of R. 

With a fresh install of R 4.1.0 and new installs of the required packages, *and* running R using this call
`Rgui.exe --vanilla`
I can replicate the crash. Here's the Windows event log for that run (using Rgui in vanilla mode):
```
Faulting application name: Rgui.exe, version: 4.10.14781.0, time stamp: 0x60a37daa
Faulting module name: randomForest.dll, version: 0.0.0.0, time stamp: 0x60b5a53b
Exception code: 0xc0000005
Fault offset: 0x0000000000001b42
Faulting process id: 0x2e80
Faulting application start time: 0x01d75acc6d8b2163
Faulting application path: C:\Program Files\R\R-4.1.0\bin\x64\Rgui.exe
Faulting module path: C:\Users\Tim\Documents\R\win-library\4.1\randomForest\libs\x64\randomForest.dll
Report Id: 7f87d240-2e4f-47af-bfc6-acf7e29e4063
Faulting package full name: 
Faulting package-relative application ID: 
```

Here's all console output from a `vanilla` session just before making the predict call (which causes it to crash).
```
R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(foreach)
> library(randomForest)
randomForest 4.6-14
Type rfNews() to see new features/changes/bug fixes.
> library(iterators)
> library(parallel)
> library(doParallel)
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] doParallel_1.0.16   iterators_1.0.13    randomForest_4.6-14 foreach_1.5.1      

loaded via a namespace (and not attached):
[1] compiler_4.1.0   codetools_0.2-18
> numCores <- 3
> ntrees <- 8000
> treeSubs <- ntrees/numCores
> # initialize
> cl <- makeCluster(numCores)
> registerDoParallel(cl)
> 
> # dummy datasets
> x <- as.data.frame(matrix(runif(10000), 2000))
> y <- gl(2, 1000)
> 
> parRf <- foreach(ntree = rep(treeSubs,numCores), .combine = randomForest::combine,
+                  .packages = 'randomForest', .multicombine = TRUE) %dopar%
+   randomForest(x=x, y=y,
+                importance=TRUE,mtry=2,ntree = ntree,
+                replace = TRUE
+   )
> 
> stopCluster(cl)
> 
> z <- matrix(runif(1000), 200)
> pred <- predict(parRf, z, type = "prob")
```

5. You haven't yet said you can not replicate this. Is that the case?

**Comment by HenrikBengtsson** [comment]
I can reproduce the segfault when using your `parRf` in R 4.1.0 on Linux (Ubuntu 18.04);

```r
library(randomForest)
## randomForest 4.6-14
## Type rfNews() to see new features/changes/bug fixes.
parRf <- readRDS("parRF_object.rds")
set.seed(42)
z <- matrix(runif(1000), nrow = 200, ncol = 5)
pred <- predict(parRf, z, type = "prob")

##  *** caught segfault ***
## address 0xfffffffffffffffa, cause 'memory not mapped'
## 
## Traceback:
##  1: predict.randomForest(parRf, z, type = "prob")
##  2: predict(parRf, z, type = "prob")
## 
## Possible actions:
## 1: abort (with core dump, if enabled)
## 2: normal R exit
## 3: exit R without saving workspace
## 4: exit R saving workspace
## Selection: 1
## R is aborting now ...
## Segmentation fault (core dumped)
```

A few comments for now:

1. This is a _bug_ in **randomForest** and specifically in `randomForest:::predict.randomForest()`.  A function should never cause R to segfault - that is always a bug regardless what you throw at.

2. This has most likely nothing to do with **foreach**

3. I suspect this has to do with not doing proper random number generation (RNG) when running in parallel, resulting in a sample with linear dependencies or similar that `predict()` for `randomForest` never anticipated.

I'll comment more later.

```r
> sessionInfo()
R version 4.1.0 Patched (2021-05-18 r80320)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /home/hb/software/R-devel/R-4-1-branch/lib/R/lib/libRblas.so
LAPACK: /home/hb/software/R-devel/R-4-1-branch/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] randomForest_4.6-14

loaded via a namespace (and not attached):
[1] compiler_4.1.0
```

**Comment by HenrikBengtsson** [comment]
I can also reproduce the core dump on my Linux machine when I set:

```r
numCores <- 3
```

and run the same code.  

Thus, the bug in `randomForest:::predict.randomForest()` is not OS specific.

**Comment by HenrikBengtsson** [comment]
Next step, find a much smaller example where it crashes.  I can reproduce the segfault with:

```r
numCores <- 3
ntrees <- 4
```

This runs _much faster_ and with much less RAM, which will help to narrow in on the bug.

**Comment by HenrikBengtsson** [comment]
Next step. Drop _parallelization_, i.e. skip setting up a parallel cluster and replace `%dopar%` with `%do%`;

```r
parRf <- foreach(ntree = ntree) %do% {
  randomForest(x=x, y=y, importance=TRUE, mtry=2, ntree=ntree, replace=TRUE)
}
```

Yup, this still segfaults.  This means we can most likely reproduce it will a base R lapply call;

```r

parRf <- lapply(ntree, function(ntree) {
  randomForest(x=x, y=y, importance=TRUE, mtry=2, ntree=ntree, replace=TRUE)
})
```

Boom. Segfault!  So, definitely independent of **foreach**.

**Comment by HenrikBengtsson** [comment]
Keep pushing toward a minimal reproduce example. It's sufficient to use:

```r
parRf <- lapply(ntree, function(ntree) {
  randomForest(x=x, y=y, ntree=ntree)
})
```

to reproduce the problem.  The fewer things involved, the easier it is to identify the problem, and eventually for the package maintainer to reproduce.

PS. @tghoward, I'm posting all this intermediate comments to share how I work to narrow in on weird bugs.

**Comment by HenrikBengtsson** [comment]
Finally, to the real cause.  Since I can now can reproduce the segfault in less than a second using on vanilla R and the **randomForest** package, I could focus on the input to `randomForest()`.

My original hunch was improper parallel RNG resulting in linear dependencies (or "something"). However, since I can now reproduce it in sequential mode, it's unlikely.  But just to be sure, I ran:

```r
parRf <- lapply(ntree, function(ntree) {
  set.seed(42)
  randomForest(x=x, y=y, ntree=ntree)
})
```

and I tried with different seeds. It segfaults all the time. Thus, I conclude it has nothing to do with RNG.

Next, I tried to with even `numCores = 2`, and sure enough, I can get it to segfault with:

```
numCores <- 2
ntrees <- 3
```

However, no matter what value of `ntrees` I try with, I cannot get it to crash with `numCores = 1`.  ... and that got me to look at our:

```r
treeSubs <- ntrees / numCores
ntree <- rep(treeSubs, times = numCores)
```

Notice that `treeSubs` is a non-integer in all the reproducible example.  Our different `treeSubs` values tests and all of the non-integers ones segfault:

```r
> 8000/3
[1] 2666.667
> 8000/61
[1] 131.1475
> 8000/62
[1] 129.0323
> 8000/63
[1] 126.9841
> 8000/64     ## <== works
[1] 125
> 4/3
[1] 1.333
> 3/2
[1] 1.5
```

**Comment by HenrikBengtsson** [comment]
Finally, here's a minimal reproduce example:

```r
library(randomForest)
set.seed(42)
x <- matrix(1:2, ncol=1)
y <- as.factor(1:2)
ntree <- 1.5 ## <= non-integer 'ntree' causes segfault
parRf <- lapply(1:2, function(ii) randomForest(x=x, y=y, ntree=ntree))
parRf <- do.call(randomForest::combine, parRf)
pred <- predict(parRf, x)


```r
$ R --quiet --vanilla
> library(randomForest)
randomForest 4.6-14
Type rfNews() to see new features/changes/bug fixes.
> set.seed(42)
> x <- matrix(1:2, ncol=1)
> y <- as.factor(1:2)
> ntree <- 1.5 ## <= non-integer 'ntree' causes segfault
> parRf <- lapply(1:2, function(ii) randomForest(x=x, y=y, ntree=ntree))
Warning messages:
1: In matrix(rfout$errtr, nclass + 1, ntree, dimnames = list(c("OOB",  :
  data length [4] is not a sub-multiple or multiple of the number of rows [3]
2: In matrix(rfout$errtr, nclass + 1, ntree, dimnames = list(c("OOB",  :
  data length [4] is not a sub-multiple or multiple of the number of rows [3]
> parRf <- do.call(randomForest::combine, parRf)
> pred <- predict(parRf, x)

 *** caught segfault ***
address 0xffffffffffffffff, cause 'memory not mapped'

Traceback:
 1: predict.randomForest(parRf, x)
 2: predict(parRf, x)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 1
R is aborting now ...
Segmentation fault (core dumped)
```

```r
$ R --quiet --vanilla
> library(randomForest)
randomForest 4.6-14
Type rfNews() to see new features/changes/bug fixes.
> sessionInfo()
R version 4.1.0 Patched (2021-05-18 r80320)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /home/hb/software/R-devel/R-4-1-branch/lib/R/lib/libRblas.so
LAPACK: /home/hb/software/R-devel/R-4-1-branch/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] randomForest_4.6-14

loaded via a namespace (and not attached):
[1] compiler_4.1.0
> 
```

**Comment by HenrikBengtsson** [comment]
@tghoward, can you please report this to the maintainer of **randomForest** (https://cran.r-project.org/web/packages/randomForest/index.html)?  Please CC me in your email.

When done, please close this issue.

PS. My only interest in this was that if it fell into the realm of parallization, I wanted to see if there was something specific when doing parallelization.  If so, then I had tried to protect against it in my **futureverse**, which would also have benefitted **foreach**.  But that turned out no to be the case.

**Comment by tghoward** [comment]
@HenrikBengtsson, thanks for spending time on this and isolating the issue further. I appreciate it. Yes, I'll report to `randomForest` maintainer.

**Comment by HenrikBengtsson** [comment]
Thank you.

Now, one more last thing. I assume you're now using a workaround where you do something like:

```r
treeSubs <- round(ntrees/numCores)
```

to avoid this bug. That should do it. 

However, you must also make sure you're using a proper random number generation (RNG), which you don't do in your current script.  That'll be important for you to trust the outcomes from a statistical perspective.  The easiest, and the current recommended approach is to use the **doRNG** package, i.e.

```r
library(doRNG)
```

and then replace `%dopar%` with `%dorng%`.  That's all.  You can read more about this in https://www.jottr.org/2020/09/22/push-for-statical-sound-rng/.
