### ISSUE TITLE
Update tooling

### ISSUE THREAD

**Issue by Hong-Revo** [RevolutionAnalytics/foreach#8]
- [x] testthat over RUnit
- [x] roxygen2
- [x] Rmarkdown for vignettes
- [x] proper testing harness for reverse deps

**Comment by Hong-Revo** [comment]
Running [revdepcheck](https://github.com/r-lib/revdepcheck) in a regular Azure Pipeline is problematic, because the default agent is too small to cope with the number of reverse dependencies. With a custom VM (16 cores, 64GB memory) it works, taking about 12 hours to churn through ~680 revdeps, but may be expensive. May also need to tweak the default `revdep_check` args; a lot of packages are failing with no result, probably because of timeouts.

@henrikbengtsson @richcalaway

**Comment by HenrikBengtsson** [comment]
You could identify the central, most downloaded revdep packages and run revdep checks on those on a "regular" basis. Running it all pkgs could be done less frequently.

**Comment by Hong-Revo** [comment]
I've found the cranlogs package for getting stats on CRAN downloads. Is there anything similar for Bioconductor?

**Comment by HenrikBengtsson** [comment]
http://bioconductor.org/packages/stats/

You find it from each package page via the 'rank' badge

**Comment by HenrikBengtsson** [comment]
Looks like you've used a dated version of  roxygen2:

https://github.com/RevolutionAnalytics/foreach/blob/c808fda611b8856ce3e820e60360352311b1155f/pkg/foreach/DESCRIPTION#L32

I recommend to update to 7.0.1 and rebuild.  They made some changed when going to 7.0.0.

**Comment by HenrikBengtsson** [comment]
I'd like to suggest that you `git mv` root folder `revdep/` up to `pkg/foreach/revdep/`.    Having it with the package folder is where most people would expect to find it.  Another reason is that I can imagine that one day you might wanna split up the current content into two separate git repositories, one for the 'foreach' package and for the 'iterators' package.  (This is fairly easy to do in git - you'll still preserve the git history).

**Comment by Hong-Revo** [comment]
Ooh, they finally updated roxygen2 to support R6 classes! Thanks for the heads up.
